[tool.poetry]
name = "replay-rec"
version = "0.6.1"
description = "RecSys Library"
authors = ["AI Lab, Sber",
           "Alexey Vasilev <AVaVasilyev@sberbank.ru>",
           "Yan-Martin Tamm <YYTamm@sberbank.ru>",
           "Anna Volodkevich <AAVolodkevich@sberbank.ru>",
           "Boris Shminke",
           "Alexander Sidorenko",
           "Roza Aysina"]
readme = "README.md"
homepage = "https://github.com/sberbank-ai-lab/RePlay"
repository = "https://github.com/sberbank-ai-lab/RePlay"
classifiers = [
    "Programming Language :: Python :: 3.7",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Typing :: Typed"
]
packages = [
    { include = "replay" }
]

[tool.poetry.dependencies]
python = ">=3.6.2, <3.10"
pytorch-ignite = "*"
lightfm = "*"
lightautoml = "*"
numpy = [
  {version = ">=1.20.0", python = ">=3.7"},
  {version = "*", python = "<3.7"}
]
optuna = "*"
pandas = "*"
psutil = "*"
pyspark = "^3.0.0"
scipy = "*"
scikit-learn = "*"
statsmodels = "*"
torch = "*"
numba = ">=0.50"
llvmlite = ">=0.32.1"
seaborn = "*"
nevergrad = "*"
pyarrow = "*"
implicit = "*"

[tool.poetry.dev-dependencies]
# dev only
# visualization
jupyter = "*"
jupyterlab = "*"
matplotlib = "*"
# testing
pytest = "5.4.3"
pytest-cov = "2.9.0"
parameterized = "0.7.4"
# style
flake8 = "*"
black = "*"
pre-commit = "*"
pylint = "*"
# docs
Sphinx = "*"
sphinx-rtd-theme = "*"
sphinx-autodoc-typehints = "*"
docutils = "=0.16"
recommonmark = "*"
sphinx-markdown-tables = "*"
ghp-import = "*"
# emacs dependencies
rope = "*"
virtualenv = "*"
# stubs
data-science-types = "*"
pyspark-stubs = "*"

[tool.black]
line-length = 79

[build-system]
build-backend = "poetry.masonry.api"
