[tool.poetry]
name = "replay-rec"
version = "0.6.0"
description = "RecSys Library"
authors = ["Boris Shminke <Shminke.B.A@sberbank.ru>",
           "Alexey Vasilev <AVaVasilyev@sberbank.ru>",
           "Yan-Martin Tamm <YYTamm@sberbank.ru>",
           "Anna Volodkevich",
           "Alexander Sidorenko",
           "Roza Aysina"]
readme = "README.md"
homepage = "https://github.com/sberbank-ai-lab/RePlay"
repository = "https://github.com/sberbank-ai-lab/RePlay"
classifiers = [
    "Programming Language :: Python :: 3.7",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Typing :: Typed"
]
packages = [
    { include = "replay" }
]

[tool.poetry.dependencies]
python = "^3.6.1"
pytorch-ignite = "*"
lightfm = "*"
lightautoml = "*"
numpy = "<1.21"
optuna = "*"
pandas = "*"
psutil = "*"
pyspark = "*"
scipy = "*"
scikit-learn = "*"
statsmodels = "*"
torch = "*"
numba = "*"
llvmlite = "*"
seaborn = "*"
nevergrad = "*"

[tool.poetry.dev-dependencies]
# fixing versions of package dependencies (non-dev)
lightfm = "1.15"
pandas = "1.0.5"
pyspark = "3.0.0"
pyarrow = "0.17.1"
torch = "1.5.1"
pytorch-ignite = "0.3.0"
statsmodels = "0.11.1"
implicit = "0.4.4"
psutil = "5.7.0"
llvmlite = "0.33"
scikit-learn = "0.23.1"
# dev only
# visualization
jupyter = "1.0.0"
jupyterlab = "2.1.5"
matplotlib = "3.2.2"
# testing
pytest = "5.4.3"
pytest-cov = "2.9.0"
parameterized = "0.7.4"
# style
flake8 = "3.8.3"
black = "19.10b0"
pre-commit = "2.6.0"
#mypy = "0.782"
pylint = "2.5.3"
# docs
Sphinx = "3.1.2"
sphinx-rtd-theme = "0.5.0"
sphinx-autodoc-typehints = "1.11.0"
recommonmark = "*"
sphinx-markdown-tables = "*"
# emacs dependencies
rope = "0.17.0"
virtualenv = "20.0.9"
# stubs
data-science-types = "0.2.16"
pyspark-stubs = "3.0.0"

[tool.black]
line-length = 79

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
