# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_docs:
    needs: install
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: pip install -U Sphinx sphinx-rtd-theme sphinx-autodoc-typehints recommonmark sphinx-markdown-tables
      - run: cd docs
      - run: mkdir -p _static
      - run: make clean html

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install package
        run: |
          sh ./install.sh
          . ./venv/bin/activate
      -name: pycodestyle
        run: pycodestyle --ignore=E203,E231,E501,W503,W605 --max-doc-length=160 replay tests
      -name: pylint
        run: pylint --rcfile=.pylintrc replay
      -name: pytest
        run: pytest --cov=replay --cov-report=term-missing --doctest-modules replay --cov-fail-under=93 tests
